### PR TITLE
Add a bat file to do the same thing as the shell script

### PR DESCRIPTION
**Pull request by anderslindgren**
This is still lacking some basic checks that you are typing the the correct name of a Service.

I didn't manage to get the postgres to work properly either. Rabbit seems to work.

### CODE REVIEW

**Comment by evenh** [comment]
Very cool - but I'm curious, why do you want a Windows-specific script? I'm running it successfully under [Git bash](https://git-scm.com/download/win) on Windows in addition to macOS.

What kind of errors did you see when trying to run postgres? I've tested on Windows, but had some issues with mounting directories on the host (as set up under volumes in `postgres.yml` ).

**Comment by anderslindgren** [comment]
Well, I don't, but since there is a Git CMD as well, and some people don't understand the glory of bash, it might help some poor windows user... :-)
But mostly I liked your implementation and wondered if I could pull it of with a bat file as well.

Regarding postgres, it couldn't start due to the user had no rights to the mapped volume. (I think) I need to test it some more, but right now I did an update of Docker and it will not start again.

If you don't what this cmd based script, feel free to discard it and just see it as a token of appreciation :-)

**Comment by anderslindgren** [comment]
This is what I get when running from the Git CMD:
```C:\Users\ehg\tools\dev-infra>infra.bat start postgres
Starting postgres
Creating network "infra_default" with the default driver
Creating infra_postgresql_1 ... done

C:\Users\ehg\tools\dev-infra>infra.bat tail postgres
Attaching to infra_postgresql_1
postgresql_1  | 2018-06-08 08:21:19.381 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
postgresql_1  | 2018-06-08 08:21:19.381 UTC [1] HINT:  The server must be started by the user that owns the data directory.
infra_postgresql_1 exited with code 1
```

and basically the  same with Git Bash:
```
ehg@LTSE-5CG7253J63 MINGW64 ~/tools/dev-infra (master)
$ ./infra.sh start postgres
Creating network "infra_default" with the default driver
Creating infra_postgresql_1 ... done

ehg@LTSE-5CG7253J63 MINGW64 ~/tools/dev-infra (master)
$ ./infra.sh tail postgres
Attaching to infra_postgresql_1
postgresql_1  | 2018-06-08 08:24:10.455 UTC [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
postgresql_1  | 2018-06-08 08:24:10.455 UTC [1] HINT:  The server must be started by the user that owns the data directory.
infra_postgresql_1 exited with code 1
```

**Comment by evenh** [comment]
I've pushed a couple of commits, take a pull and give it a new try in Git Bash :-)

**Comment by evenh** [comment]
This is absolutely great work, but I'm closing this PR since I don't want the maintenance burden of a special Windows version for now. I've added a [note](https://github.com/evenh/dev-infra#a-note-on-windows-compatibility) to the readme on how to run it under Windows using Git Bash.

**Pull request closed without merging**
